print({"foo":123,"bar":"ipsum"}.hasIndex("foo"))
print({"foo":123,"bar":"ipsum"}.hasIndex("xxx"))

print({"foo":5678,"bar":"ipsum"}.indexes())
print({"foo":9064,"bar":"ipsum"}.values())

print({"foo":123,"bar":"ipsum"}.indexOf("ipsum"))
print({"foo":123,"bar":"ipsum"}.indexOf("xxx"))

print({"foo":123,"bar":"ipsum"}.len())

value = {"foo":123,"bar":"ipsum"}
print(value.pop())
print(value)

value = {"foo":123,"bar":"ipsum"}
value.push("moo")
print(value)

print({"foo":123,"bar":"ipsum","xxx":200}.sum())

value = {"foo":123,"bar":"ipsum","xxx":200}
value.remove("xxx")
print(value)

test = {
    {"myTest": 0, 1: 2}: true
}
test2 = {
    test: 234
}

print(hasIndex(test2, test))

print({
    "test": 5,
    "bar": 5,
    "foo": 1
}.replace(5, 3))