value = 1337
value2 = 347

print(abs(value))
print(acos(value))
print(asin(value))
print(atan(value))
print(tan(value))
print(ceil(value))
print(cos(value))
print(floor(value))
print(sin(value))
print(round(value))
print(sqrt(value))
print(pi)

print(bitwise("&", value, value2))
print(bitwise("|", value, value2))
print(bitwise("^", value, value2))
print(bitwise("<<", value, value2))
print(bitwise(">>", value, value2))
print(bitwise(">>>", value, value2))
print(bitwise("~", value))

print round(12345, -3)