print ("1.23".val)
print ("1,23".val)
print ("1".val)
print ("1e".val)
print "1.234,56".val
print "1,23,4.56".val
print "1,23,4.5,6".val
print "1.234,56 wwa".val
print "1  ,23,4.56".val
print "   1,23,4.5   ".val
print "123.443.42".val
print "+12.5".val
print "-12.5".val
print "23E-1".val
print "23E+1".val
print "23.2E-1".val
print "23.2E+1".val
print "1e0".val
print "+1.23e3".val
print "0.000123e3".val
print "0x1.23p4".val